/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:46b9df86-0323-4de7-bbed-5d3d0957f5ae",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yCA54KSCK",
    "aws_user_pools_web_client_id": "40hr6o049dgc1je65ou5ugh100",
    "oauth": {
        "domain": "oathdemoa463bcce-a463bcce-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://wafalab.awsps.myinstance.com/",
        "redirectSignOut": "http://localhost:3000/,https://wafalab.awsps.myinstance.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
